# Generated by Django 4.1 on 2023-06-04 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dataspace", "0033_os_base_os_peak_os_task_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="train_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("L1_I", models.FloatField()),
                ("L1_D", models.FloatField()),
                ("L2", models.FloatField()),
                ("L3", models.FloatField()),
                ("Max_Hz", models.FloatField()),
                ("Memory", models.FloatField()),
                ("Base_Pointers", models.FloatField()),
                ("Peak_Pointers", models.FloatField()),
                ("nominal", models.FloatField()),
                (
                    "OS",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dataspace.os"
                    ),
                ),
            ],
        ),
    ]
