# Generated by Django 4.1 on 2023-06-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mlPredict", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="train_data",
            name="cores",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
