# Generated by Django 4.1 on 2023-05-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CFP2017_ratediv",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("test_sponsor", models.CharField(max_length=128)),
                ("System_Name", models.CharField(max_length=128)),
                ("HTML", models.CharField(max_length=128)),
                ("CSV", models.CharField(max_length=128)),
                ("Text", models.CharField(max_length=128)),
                ("PDF", models.CharField(max_length=128)),
                ("Config", models.CharField(max_length=128)),
                ("base_copies", models.IntegerField()),
                ("hw_ncores", models.IntegerField()),
                ("hw_nchips", models.IntegerField()),
                ("hw_nthreadspercore", models.IntegerField()),
                ("basemean", models.FloatField()),
                ("peakmean", models.FloatField()),
                ("baseenergymean", models.FloatField()),
                ("peakenergymean", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CFP2017_speeddiv",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("test_sponsor", models.CharField(max_length=128)),
                ("System_Name", models.CharField(max_length=128)),
                ("HTML", models.CharField(max_length=128)),
                ("CSV", models.CharField(max_length=128)),
                ("Text", models.CharField(max_length=128)),
                ("PDF", models.CharField(max_length=128)),
                ("Config", models.CharField(max_length=128)),
                ("base_copies", models.IntegerField()),
                ("hw_ncores", models.IntegerField()),
                ("hw_nchips", models.IntegerField()),
                ("hw_nthreadspercore", models.IntegerField()),
                ("basemean", models.FloatField()),
                ("peakmean", models.FloatField()),
                ("baseenergymean", models.FloatField()),
                ("peakenergymean", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CINT2017_ratediv",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("test_sponsor", models.CharField(max_length=128)),
                ("System_Name", models.CharField(max_length=128)),
                ("HTML", models.CharField(max_length=128)),
                ("CSV", models.CharField(max_length=128)),
                ("Text", models.CharField(max_length=128)),
                ("Config", models.CharField(max_length=128)),
                ("PDF", models.CharField(max_length=128)),
                ("base_copies", models.IntegerField()),
                ("hw_ncores", models.IntegerField()),
                ("hw_nchips", models.IntegerField()),
                ("hw_nthreadspercore", models.IntegerField()),
                ("basemean", models.FloatField()),
                ("peakmean", models.FloatField()),
                ("baseenergymean", models.FloatField()),
                ("peakenergymean", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CINT2017_speeddiv",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("test_sponsor", models.CharField(max_length=128)),
                ("System_Name", models.CharField(max_length=128)),
                ("HTML", models.CharField(max_length=128)),
                ("CSV", models.CharField(max_length=128)),
                ("Text", models.CharField(max_length=128)),
                ("Config", models.CharField(max_length=128)),
                ("PDF", models.CharField(max_length=128)),
                ("base_copies", models.IntegerField()),
                ("hw_ncores", models.IntegerField()),
                ("hw_nchips", models.IntegerField()),
                ("hw_nthreadspercore", models.IntegerField()),
                ("basemean", models.FloatField()),
                ("peakmean", models.FloatField()),
                ("baseenergymean", models.FloatField()),
                ("peakenergymean", models.FloatField()),
            ],
        ),
    ]
