# Generated by Django 4.1 on 2023-05-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataspace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfp2017_ratediv",
            name="p_id",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_speeddiv",
            name="p_id",
            field=models.IntegerField(default=100000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_ratediv",
            name="p_id",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_speeddiv",
            name="p_id",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cfp2017_ratediv",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cfp2017_speeddiv",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cint2017_ratediv",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cint2017_speeddiv",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
