# Generated by Django 4.1 on 2023-05-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataspace", "0002_cfp2017_ratediv_p_id_cfp2017_speeddiv_p_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfp2017_ratediv",
            name="PS",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_speeddiv",
            name="PS",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_ratediv",
            name="PS",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_speeddiv",
            name="PS",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
