# Generated by Django 4.1 on 2023-05-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataspace", "0004_cfp2017_speeddiv_sw_parallel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfp2017_speeddiv",
            name="base_threads",
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_speeddiv",
            name="base_threads",
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
    ]
