# Generated by Django 4.1 on 2023-05-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataspace", "0005_cfp2017_speeddiv_base_threads_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfp2017_speeddiv",
            name="base_threads",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cint2017_speeddiv",
            name="base_threads",
            field=models.IntegerField(),
        ),
    ]
