# Generated by Django 4.1 on 2023-05-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataspace", "0006_alter_cfp2017_speeddiv_base_threads_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cfp2017_speeddiv",
            name="base_copies",
        ),
        migrations.RemoveField(
            model_name="cint2017_speeddiv",
            name="base_copies",
        ),
    ]
