# Generated by Django 4.1 on 2023-05-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataspace", "0010_alter_cfp2017_ratediv_hard_soft_peak_pointers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cfp2017_ratediv_hard_soft",
            old_name="Other_jemalloc",
            new_name="Other",
        ),
        migrations.RenameField(
            model_name="cfp2017_speeddiv_hard_soft",
            old_name="Other_jemalloc",
            new_name="Other",
        ),
        migrations.RenameField(
            model_name="cint2017_ratediv_hard_soft",
            old_name="Other_jemalloc",
            new_name="Other",
        ),
        migrations.RenameField(
            model_name="cint2017_speeddiv_hard_soft",
            old_name="Other_jemalloc",
            new_name="Other",
        ),
    ]
