# Generated by Django 4.1 on 2023-05-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dataspace",
            "0011_rename_other_jemalloc_cfp2017_ratediv_hard_soft_other_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cfp2017_ratediv_hard_soft",
            name="Storage",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_speeddiv_hard_soft",
            name="Storage",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_ratediv_hard_soft",
            name="Storage",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_speeddiv_hard_soft",
            name="Storage",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
