# Generated by Django 4.1 on 2023-05-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataspace", "0016_remove_cfp2017_ratediv_hard_soft_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfp2017_ratediv_hard_soft",
            name="Details",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_ratediv_hard_soft",
            name="NICs_Connected_Speed",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_ratediv_hard_soft",
            name="NICs_Enabled_FW_OS",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_ratediv_hard_soft",
            name="NICs_Installed",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_ratediv_hard_soft",
            name="Other_HW_Model",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_ratediv_hard_soft",
            name="Other_Storage",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_ratediv_hard_soft",
            name="Power_Supply",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_ratediv_hard_soft",
            name="Storage_Model",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_speeddiv_hard_soft",
            name="Details",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_speeddiv_hard_soft",
            name="NICs_Connected_Speed",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_speeddiv_hard_soft",
            name="NICs_Enabled_FW_OS",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_speeddiv_hard_soft",
            name="NICs_Installed",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_speeddiv_hard_soft",
            name="Other_HW_Model",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_speeddiv_hard_soft",
            name="Other_Storage",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_speeddiv_hard_soft",
            name="Power_Supply",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_speeddiv_hard_soft",
            name="Storage_Model",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_ratediv_hard_soft",
            name="Details",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_ratediv_hard_soft",
            name="NICs_Connected_Speed",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_ratediv_hard_soft",
            name="NICs_Enabled_FW_OS",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_ratediv_hard_soft",
            name="NICs_Installed",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_ratediv_hard_soft",
            name="Other_HW_Model",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_ratediv_hard_soft",
            name="Other_Storage",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_ratediv_hard_soft",
            name="Power_Supply",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_ratediv_hard_soft",
            name="Storage_Model",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_speeddiv_hard_soft",
            name="Details",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_speeddiv_hard_soft",
            name="NICs_Connected_Speed",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_speeddiv_hard_soft",
            name="NICs_Enabled_FW_OS",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_speeddiv_hard_soft",
            name="NICs_Installed",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_speeddiv_hard_soft",
            name="Other_HW_Model",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_speeddiv_hard_soft",
            name="Other_Storage",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_speeddiv_hard_soft",
            name="Power_Supply",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_speeddiv_hard_soft",
            name="Storage_Model",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
