# Generated by Django 4.1 on 2023-05-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataspace", "0019_alter_cfp2017_speeddiv_hard_soft_compiler"),
    ]

    operations = [
        migrations.AddField(
            model_name="cfp2017_ratediv_hard_soft",
            name="Backplane",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cfp2017_speeddiv_hard_soft",
            name="Backplane",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_ratediv_hard_soft",
            name="Backplane",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cint2017_speeddiv_hard_soft",
            name="Backplane",
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
