# Generated by Django 4.1 on 2023-05-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataspace", "0020_cfp2017_ratediv_hard_soft_backplane_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cfp2017_ratediv_hard_soft",
            name="Other",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="cfp2017_speeddiv_hard_soft",
            name="Other",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="cint2017_ratediv_hard_soft",
            name="Other",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="cint2017_speeddiv_hard_soft",
            name="Other",
            field=models.CharField(max_length=512),
        ),
    ]
