# Generated by Django 4.1 on 2023-06-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataspace", "0032_sponsor_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="os",
            name="base",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="os",
            name="peak",
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="os",
            name="task_number",
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
