# Generated by Django 4.1 on 2023-06-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataspace", "0033_os_base_os_peak_os_task_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="improve_peak_base",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_sponsor", models.CharField(max_length=128)),
                ("improve_score", models.FloatField()),
                ("task", models.IntegerField()),
            ],
        ),
    ]
